### ISSUE TITLE
How is browser-sync wrapped?

### ISSUE THREAD

**Issue by quinncomendant** [ustwo/docker-browser-sync#2]
From the description of this package it is implied that browser sync is somehow modified so that it works with filesystem events over NFS. How exactly is that done? In the Dockerfile I only see `npm -g install browser-sync` which is installing regular browser-sync. I don't see how this “Wraps Browser Sync”.

I'm looking for a solution to run browser-sync in docker containers using NFS running via [xhyve + coreos](https://github.com/TheNewNormal/corectl).

Thanks!

**Comment by arnau** [comment]
Hi, last time I did the tests with Virtualbox, filesystem events weren't propagated.  There is no solution I know that makes it work.

Instead, I use a polling strategy to let browser-sync do its thing.  The config files used to test this approach are in `sandbox/`.

Answering your question, browser-sync is wrapped in a docker container so instead of running `browser-sync` installed in your host machine, you run the `docker run ...` command and it will expect the very same flags.

I'm interested in what you get out of xhyve + NFS.

**Comment by quinncomendant** [comment]
Hi @arnau,

How are the files in `sandbox/` executed? As I see in the Dockerfile and examples, the normal browser-sync will be executed like, e.g., `browser-sync start --files "*.css"`.

I'll let you know how I succeed with xhyve + nfs. So far my experience using `corectl` with xhyve on os x 10.11 is a very clean and fast experience—it's great. As far as I have learned, inotify simply isn't compatible with NFS, so this may be impossible (without doing some kind of polling or rsync from the host).

**Comment by arnau** [comment]
Something on the lines of:

``` sh
docker run --rm -t \
  -p 3000:3000 \
  -p 3001:3001 \
  -v $(PWD)/sandbox:/source \
  -w /source \
  ustwo/browser-sync \
  start --config /source/config.js
```

Which could be oganised as:

``` sh
alias browser-sync="docker run --rm -t \
  -p 3000:3000 \
  -p 3001:3001 \
  -v $(PWD)/sandbox:/source \
  -w /source \
  ustwo/browser-sync

browser-sync start --config /source/config.js
```

So the last `browser-sync` command is in fact an alias for the docker command.

My current setup though involves `fswatch` to manage filesystem notifications and browser-sync only deals with injecting files to the browser reacting on `fswatch` commands.  Not ideal but reliable.
